[build]
cmd = "go build -o golang-demo"
bin = "golang-demo"
dir = "."
include_dir = ["."]
extensions = ["go"]
exclude_dir = ["vendor", "tmp"]
run_after_build = "chmod +x golang-demo"

[log]
level = "debug"
